=begin
#Ant Media Server REST API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.5.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.31

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AntmediaClient::AutowireCapableBeanFactory
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AutowireCapableBeanFactory' do
  before do
    # run before each test
    @instance = AntmediaClient::AutowireCapableBeanFactory.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AutowireCapableBeanFactory' do
    it 'should create an instance of AutowireCapableBeanFactory' do
      expect(@instance).to be_instance_of(AntmediaClient::AutowireCapableBeanFactory)
    end
  end
end
